### PR TITLE
Adding additional options including specifying the NSG name

### LINKED ISSUE #18: Warning: "address_prefix": [DEPRECATED] Use the `address_prefixes` property instead
Impacted version 2.0.0

image

### LINKED ISSUE #21: enhance NSG rule support
support custom NSG name, extend the properties supported for the NSG object

### LINKED ISSUE #22: warning: address_prefix deprecated
Warning: "address_prefix": [DEPRECATED] Use the `address_prefixes` property instead.
on /home/vsts_azpcontainer/modules/blueprint_networking.virtual_network/terraform-azurerm-caf-virtual-network-2.0.0/subnet/subnet.tf line 1, in resource "azurerm_subnet" "v_subnet":
1: resource "azurerm_subnet" "v_subnet" {

### PR DESCRIPTION
**Pull request by nyuen**
Adding all the nsg configuration options including 

source_port_ranges
destination_port_ranges
source_address_prefixes
destination_address_prefixes

Added dedicated field for nsg naming

### CODE REVIEW

**Review by arnaudlh — CHANGES_REQUESTED** [review]
thanks and good update, can you please add:
- a GitHub Issue to refer in the PR
- use the naming convention provider (as in 2.0) instead of module in your commit
- a unit and integration testing automation 
- update the changelog referring the issue (we can target version number 3.0 as its a breaking change, with 2.0) 
- verify syntax for examples (use resource_group_name instead of virtual_network_rg)

**Comment by nyuen** [comment]
Implemented changes - we need to review the usage of the new naming convention - it should probably be outside of the module otherwise we need to provides the same capabilties (name,prefix,length...)

**Comment by arnaudlh** [comment]
@nyuen feels like your PR is based on vnet 1.2 instead of 2.0

**Review by arnaudlh — APPROVED** [review]
LGTM

**Pull request merged**
